# name: Manual Workflow Trigger

# on:
#   issue_comment:
#     types: [created]

# jobs:
#   build:
#     if: contains(github.event.comment.body, '/run')
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
